version: '1.0'
services:
  app_start:
    container_name: python_start
    build: ./
    command: python app_start.py
    ports:
      - 4000:4000
    volumes:
      - ./:/app

  exchange:
    image: postgres:latest
    container_name: exchange
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exchange
    volumes:
      - ./csv_files:/docker-entrypoint-initdb.d/csv_files/
    depends_on:
      app_start:
        condition: service_completed_successfully
#    links:
#      - app_start
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
    restart: always

  app_end:
    container_name: python_end
    build: ./
    command: python python_end.py
    ports:
      - 4004:4000
    volumes:
      - ./:/app
    depends_on:
      exchange:
        condition: service_healthy
