CREATE TABLE IF NOT EXISTS products 
(
	product_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
	product_name VARCHAR(255) NOT NULL,
	CONSTRAINT products_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS brands 
(
	brand_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
	brand_name VARCHAR(255) NOT NULL,
    CONSTRAINT brands_pkey PRIMARY KEY (brand_id)
);

CREATE TABLE IF NOT EXISTS models 
(
	model_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
	model_name VARCHAR(255) NOT NULL,
	CONSTRAINT model_pkey PRIMARY KEY (model_id)
);

CREATE TABLE IF NOT EXISTS product_categories 
(
	prod_category_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
	category_name VARCHAR(255) NOT NULL,
	CONSTRAINT prod_category_pkey PRIMARY KEY (prod_category_id)
);

CREATE TABLE IF NOT EXISTS genders 
(
	gender_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
	gender_value VARCHAR(255) NOT NULL,
	CONSTRAINT gender_pkey PRIMARY KEY (gender_id)
);

CREATE TABLE IF NOT EXISTS platforms 
(
	platform_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
	platform_name VARCHAR(255) NOT NULL,
	CONSTRAINT platform_pkey PRIMARY KEY (platform_id)
);

CREATE TABLE IF NOT EXISTS types_actions 
(
	type_action_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
	action_name VARCHAR(255) NOT NULL,
	CONSTRAINT type_action_pkey PRIMARY KEY (type_action_id)
);

CREATE TABLE IF NOT EXISTS promo_action 
(
	promo_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
	product_id INTEGER NOT NULL,
	date_start_promo DATE NOT NULL,
	date_end_promo DATE NOT NULL,
	discount NUMERIC NOT NULL,
	CONSTRAINT promo_pkey PRIMARY KEY (promo_id),
	CONSTRAINT product_id FOREIGN KEY (product_id) REFERENCES products (product_id)
);

CREATE TABLE IF NOT EXISTS buyers 
(
	personal_acc_id INTEGER NOT NULL,
	buyers_cookies VARCHAR NOT NULL,
	full_name VARCHAR(255) NOT NULL,
	gender_id INTEGER NOT NULL,
	birthdate DATE NOT NULL,
	e_mail VARCHAR NOT NULL,
	telephone VARCHAR NOT NULL,
	CONSTRAINT personal_acc_pkey PRIMARY KEY (personal_acc_id),
	CONSTRAINT gender_id FOREIGN KEY (gender_id) REFERENCES genders (gender_id)
);

CREATE TABLE IF NOT EXISTS banners 
(
	banner_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
	product_id INTEGER NOT NULL,
	platform_id INTEGER NOT NULL,
	personal_acc_id INTEGER NOT NULL,
	type_action_id INTEGER NOT NULL,
	date_action DATE NOT NULL,
	time_interval TIME NOT NULL,
	CONSTRAINT banner_pkey PRIMARY KEY (banner_id),
	CONSTRAINT product_id FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT platform_id FOREIGN KEY (platform_id) REFERENCES platforms (platform_id),
    CONSTRAINT personal_acc_id FOREIGN KEY (personal_acc_id) REFERENCES buyers (personal_acc_id),
    CONSTRAINT type_action_id FOREIGN KEY (type_action_id) REFERENCES types_actions (type_action_id)
);

CREATE TABLE IF NOT EXISTS sales 
(
	order_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
	order_time DATE NOT NULL,
	personal_acc_id INTEGER NOT NULL,
	product_id INTEGER NOT NULL,
	price NUMERIC NOT NULL,
	brand_id INTEGER NOT NULL,
	model_id INTEGER NOT NULL,
	prod_category_id INTEGER NOT NULL,
	amount INTEGER NOT NULL,
	CONSTRAINT order_pkey PRIMARY KEY (order_id),
	CONSTRAINT personal_acc_id FOREIGN KEY (personal_acc_id) REFERENCES buyers (personal_acc_id),
    CONSTRAINT product_id FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT brand_id FOREIGN KEY (brand_id) REFERENCES brands (brand_id),
    CONSTRAINT model_id FOREIGN KEY (model_id) REFERENCES models (model_id),
    CONSTRAINT prod_category_id FOREIGN KEY (prod_category_id) REFERENCES product_categories (prod_category_id)
);